services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hospital'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  hospital-management-system:
    image: hospital-management-system:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hospital
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
#      - kafka

#  kafka:
#    image: confluentinc/cp-kafka:7.7.1
#    restart: "no"
#    ports:
#      - "29092:29092"
#      - "9092:9092"
#    volumes:
#      - kafka_data:/var/lib/kafka/data
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_NODE_ID: 1
#      CLUSTER_ID: 2BvOHoAhQve1FTVuv90hmQ
#      KAFKA_PROCESS_ROLES: controller,broker
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:9093
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9092"]
#      interval: 10s
#      timeout: 5s
#      start_period: 30s
#      retries: 5
#    depends_on:
#      - postgres
#    labels:
#      amplicode.image: confluent/kafka
#
#  kafkaui:
#    image: provectuslabs/kafka-ui:v0.7.2
#    restart: "no"
#    ports:
#      - "8989:8080"
#    environment:
#      DYNAMIC_CONFIG_ENABLED: "true"
#      KAFKA_CLUSTERS_0_NAME: "local-cluster"
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
#    healthcheck:
#      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit -1
#      interval: 10s
#      timeout: 5s
#      start_period: 60s
#      retries: 5
#    depends_on:
#      - kafka
#
#volumes:
#  kafka_data:
